/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandarcifrado;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.NoSuchPaddingException;
import javax.swing.*;

/**
 * 
 * @author chori
 *
 */
public class PantallaCliente extends javax.swing.JFrame {
	// private SecretKey clave;
	private Socket clienteSocket = null;
	private ObjectOutputStream os = null;
	private FileOutputStream fos = null;
	private File archivo;
	private File archivoCi;
	private ObjectOutputStream os1;
	private String direccionIP;

	/**
	 * Creates new form Pantalla
	 */
	public PantallaCliente() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		direccionIP = JOptionPane.showInputDialog("A que direccion IP vamos a mandar el archivo cifrado");

		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("...");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Enviar");
		jButton2.setEnabled(false);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(72, 72, 72)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(90, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(44, 44, 44)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton1))
						.addGap(44, 44, 44).addComponent(jButton2).addContainerGap(82, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser filechoser = new JFileChooser();
		// FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG
		// & GIF", "jpg", "png", "gif"); // Solo visibles archivos con esas extensiones
		// filechoser.setFileFilter(filtroImagen);
		int opcion = filechoser.showOpenDialog(this);
		if (opcion == JFileChooser.APPROVE_OPTION) {
			archivo = filechoser.getSelectedFile();
			jTextField1.setText(archivo.getPath());
			jButton2.setEnabled(true);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		try {
			ObjectInputStream oin = new ObjectInputStream(new FileInputStream("claveSecreta.txt"));
			Key claveSecreta = (Key) oin.readObject();
			oin.close();

			Cipher c = Cipher.getInstance("AES/ECB/PKCS5Padding");
			c.init(Cipher.ENCRYPT_MODE, claveSecreta);

			FileInputStream filein = new FileInputStream(archivo);
			CipherOutputStream out;
			int idx = archivo.getName().lastIndexOf('.');
			String terminacion = archivo.getName().substring(idx);
			out = new CipherOutputStream(new FileOutputStream("FicheroCifrado" + terminacion), c);

			int tamBloque = c.getBlockSize();
			byte[] bytes = new byte[tamBloque];

			int i = filein.read(bytes);
			while (i != -1) {
				out.write(bytes, 0, i);
				i = filein.read(bytes);
			}

			out.close();
			archivoCi = new File("FicheroCifrado" + terminacion);

			// ENVIAMOS

			clienteSocket = new Socket(direccionIP, 8080);

			os = new ObjectOutputStream(clienteSocket.getOutputStream());
			//os1 = new ObjectOutputStream(clienteSocket.getOutputStream());
			//os1.writeUTF(terminacion);
			//os1.close();
			FileInputStream ficheroStream = new FileInputStream(archivoCi);

			byte contenido[] = new byte[1024 * 4];
			i = ficheroStream.read(contenido);
			while (i != -1) {
				os.write(contenido, 0, i);
				i = ficheroStream.read(contenido);
			}
			ficheroStream.close();
			os.close();

		} catch (FileNotFoundException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (NoSuchAlgorithmException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (NoSuchPaddingException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InvalidKeyException ex) {
			Logger.getLogger(PantallaCliente.class.getName()).log(Level.SEVERE, null, ex);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(jButton1, "Error esa dirección no es valida");
		}

	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaCliente().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
